/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApiTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastUsedAt', 'lastUsedIp', 'prefix', 'token', 'tokenDigest', 'updatedAt', 'userId'] as const
  $columns = ApiTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare lastUsedIp: string | null
  @column()
  declare prefix: string
  @column()
  declare token: string | null
  @column()
  declare tokenDigest: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AssetFolderSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'path', 'updatedAt'] as const
  $columns = AssetFolderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare path: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AssetSchema extends BaseModel {
  static $columns = ['alt', 'caption', 'createdAt', 'deletedAt', 'description', 'filename', 'focalX', 'focalY', 'folder', 'height', 'id', 'key', 'mimeType', 'size', 'title', 'updatedAt', 'variants', 'width'] as const
  $columns = AssetSchema.$columns
  @column()
  declare alt: string | null
  @column()
  declare caption: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare filename: string
  @column()
  declare focalX: number
  @column()
  declare focalY: number
  @column()
  declare folder: string
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare mimeType: string
  @column()
  declare size: number
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare variants: any
  @column()
  declare width: number | null
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorId', 'actorLabel', 'actorType', 'createdAt', 'id', 'ip', 'metadata', 'subjectId', 'subjectLabel', 'subjectType', 'userAgent', 'userId', 'via'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorId: number | null
  @column()
  declare actorLabel: string
  @column()
  declare actorType: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ip: string | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare metadata: any
  @column()
  declare subjectId: number | null
  @column()
  declare subjectLabel: string | null
  @column()
  declare subjectType: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number | null
  @column()
  declare via: string
}

export class BlockTypeSchema extends BaseModel {
  static $columns = ['builtIn', 'category', 'createdAt', 'defaults', 'deprecated', 'description', 'fields', 'icon', 'id', 'label', 'slug', 'updatedAt', 'version'] as const
  $columns = BlockTypeSchema.$columns
  @column({ consume: (value: unknown) => Boolean(value) })
  declare builtIn: boolean
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare defaults: any
  @column({ consume: (value: unknown) => Boolean(value) })
  declare deprecated: boolean
  @column()
  declare description: string | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare fields: any
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class CollectionSchema extends BaseModel {
  static $columns = ['buildConfig', 'categoriesCollectionId', 'createdAt', 'description', 'enableBlocks', 'enableBody', 'fields', 'icon', 'id', 'name', 'notificationEmails', 'notificationEvents', 'singularName', 'slug', 'tagsCollectionId', 'updatedAt', 'urlPrefix'] as const
  $columns = CollectionSchema.$columns
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare buildConfig: any
  @column()
  declare categoriesCollectionId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ consume: (value: unknown) => Boolean(value) })
  declare enableBlocks: boolean
  @column({ consume: (value: unknown) => Boolean(value) })
  declare enableBody: boolean
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare fields: any
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notificationEmails: string | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare notificationEvents: any
  @column()
  declare singularName: string
  @column()
  declare slug: string
  @column()
  declare tagsCollectionId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare urlPrefix: string | null
}

export class ContentReferenceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'kind', 'ownerId', 'ownerType', 'path', 'position', 'refId', 'refType'] as const
  $columns = ContentReferenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare ownerId: number
  @column()
  declare ownerType: string
  @column()
  declare path: string
  @column()
  declare position: number
  @column()
  declare refId: string
  @column()
  declare refType: string
}

export class DeviceAuthorizationSchema extends BaseModel {
  static $columns = ['approvedAt', 'createdAt', 'deniedAt', 'deviceCode', 'expiresAt', 'hostname', 'id', 'label', 'purpose', 'updatedAt', 'userCode', 'userId'] as const
  $columns = DeviceAuthorizationSchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deniedAt: DateTime | null
  @column()
  declare deviceCode: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hostname: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string | null
  @column()
  declare purpose: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userCode: string
  @column()
  declare userId: number | null
}

export class EntrySchema extends BaseModel {
  static $columns = ['blocks', 'body', 'categoryEntryId', 'collectionId', 'createdAt', 'data', 'deletedAt', 'id', 'locale', 'lockVersion', 'publishAt', 'publishedAt', 'seo', 'slug', 'status', 'title', 'translationGroupId', 'unpublishAt', 'updatedAt'] as const
  $columns = EntrySchema.$columns
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare blocks: any
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare body: any | null
  @column()
  declare categoryEntryId: number | null
  @column()
  declare collectionId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare data: any
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare lockVersion: number
  @column.dateTime()
  declare publishAt: DateTime | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare seo: any
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column()
  declare translationGroupId: number | null
  @column.dateTime()
  declare unpublishAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EntryVersionSchema extends BaseModel {
  static $columns = ['blocks', 'body', 'createdAt', 'data', 'entryId', 'id', 'seo', 'title', 'userId'] as const
  $columns = EntryVersionSchema.$columns
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare blocks: any | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare body: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare data: any
  @column()
  declare entryId: number
  @column({ isPrimary: true })
  declare id: number
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare seo: any
  @column()
  declare title: string
  @column()
  declare userId: number | null
}

export class FormEmailSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'enabled', 'formId', 'fromField', 'id', 'kind', 'recipients', 'subject', 'updatedAt'] as const
  $columns = FormEmailSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ consume: (value: unknown) => Boolean(value) })
  declare enabled: boolean
  @column()
  declare formId: number
  @column()
  declare fromField: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare recipients: string | null
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FormSubmissionSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'formId', 'id', 'ip', 'meta', 'status', 'updatedAt', 'userAgent'] as const
  $columns = FormSubmissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare data: any
  @column()
  declare formId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ip: string | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare meta: any | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
}

export class FormSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'fields', 'id', 'notifyEmails', 'slug', 'status', 'submitLabel', 'submitUrl', 'successMessage', 'title', 'updatedAt', 'webhookUrl'] as const
  $columns = FormSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare fields: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notifyEmails: string | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare submitLabel: string
  @column()
  declare submitUrl: string | null
  @column()
  declare successMessage: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare webhookUrl: string | null
}

export class GlobalSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'deletedAt', 'description', 'fields', 'icon', 'id', 'lockVersion', 'name', 'slug', 'updatedAt'] as const
  $columns = GlobalSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare data: any
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare fields: any
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lockVersion: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PageVersionSchema extends BaseModel {
  static $columns = ['blocks', 'createdAt', 'frontmatter', 'id', 'pageId', 'seo', 'title', 'userId'] as const
  $columns = PageVersionSchema.$columns
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare blocks: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare frontmatter: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pageId: number
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare seo: any
  @column()
  declare title: string
  @column()
  declare userId: number | null
}

export class PageSchema extends BaseModel {
  static $columns = ['blocks', 'categoryEntryId', 'createdAt', 'deletedAt', 'fields', 'frontmatter', 'id', 'locale', 'lockVersion', 'parentId', 'path', 'publishAt', 'publishedAt', 'seo', 'slug', 'status', 'title', 'translationGroupId', 'unpublishAt', 'updatedAt'] as const
  $columns = PageSchema.$columns
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare blocks: any
  @column()
  declare categoryEntryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare fields: any
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare frontmatter: any
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare lockVersion: number
  @column()
  declare parentId: number | null
  @column()
  declare path: string
  @column.dateTime()
  declare publishAt: DateTime | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare seo: any
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column()
  declare translationGroupId: number | null
  @column.dateTime()
  declare unpublishAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'dedupAt', 'dedupId', 'dedupTtl', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare dedupAt: bigint | number | null
  @column()
  declare dedupId: string | null
  @column()
  declare dedupTtl: bigint | number | null
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RedirectSchema extends BaseModel {
  static $columns = ['createdAt', 'destination', 'hits', 'id', 'isActive', 'lastHitAt', 'notes', 'source', 'statusCode', 'updatedAt'] as const
  $columns = RedirectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare destination: string
  @column()
  declare hits: number
  @column({ isPrimary: true })
  declare id: number
  @column({ consume: (value: unknown) => Boolean(value) })
  declare isActive: boolean
  @column.dateTime()
  declare lastHitAt: DateTime | null
  @column()
  declare notes: string | null
  @column()
  declare source: string
  @column()
  declare statusCode: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isSystem', 'name', 'permissions', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ consume: (value: unknown) => Boolean(value) })
  declare isSystem: boolean
  @column()
  declare name: string
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare permissions: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ServiceTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'createdById', 'description', 'id', 'lastUsedAt', 'lastUsedIp', 'name', 'prefix', 'revokedAt', 'roleId', 'token', 'tokenDigest', 'updatedAt'] as const
  $columns = ServiceTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdById: number | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare lastUsedIp: string | null
  @column()
  declare name: string
  @column()
  declare prefix: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare roleId: number
  @column()
  declare token: string | null
  @column()
  declare tokenDigest: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'secrets', 'updatedAt', 'value'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare secrets: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare value: any
}

export class TaggingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'position', 'tagEntryId', 'taggableId', 'taggableType', 'updatedAt'] as const
  $columns = TaggingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare position: number
  @column()
  declare tagEntryId: number
  @column()
  declare taggableId: number
  @column()
  declare taggableType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TranslationGroupSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'kind', 'updatedAt'] as const
  $columns = TranslationGroupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UpgradeSchema extends BaseModel {
  static $columns = ['createdAt', 'externalId', 'externalUrl', 'finishedAt', 'fromVersion', 'id', 'message', 'requestedById', 'status', 'toVersion', 'updatedAt', 'via'] as const
  $columns = UpgradeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalId: string | null
  @column()
  declare externalUrl: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column()
  declare fromVersion: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string | null
  @column()
  declare requestedById: number | null
  @column()
  declare status: string
  @column()
  declare toVersion: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare via: string
}

export class UserSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ipAddress', 'lastSeenAt', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = UserSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column.dateTime()
  declare lastSeenAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'recoveryCodeDigests', 'roleId', 'totpEnabledAt', 'totpSecret', 'updatedAt', 'verifiedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare recoveryCodeDigests: any | null
  @column()
  declare roleId: number | null
  @column.dateTime()
  declare totpEnabledAt: DateTime | null
  @column()
  declare totpSecret: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare verifiedAt: DateTime | null
}

export class WebhookDeliverySchema extends BaseModel {
  static $columns = ['attempt', 'createdAt', 'durationMs', 'error', 'event', 'id', 'payload', 'responseBody', 'responseStatus', 'success', 'webhookId'] as const
  $columns = WebhookDeliverySchema.$columns
  @column()
  declare attempt: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number | null
  @column()
  declare error: string | null
  @column()
  declare event: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare payload: string
  @column()
  declare responseBody: string | null
  @column()
  declare responseStatus: number | null
  @column({ consume: (value: unknown) => Boolean(value) })
  declare success: boolean
  @column()
  declare webhookId: number
}

export class WebhookSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'eventFilters', 'events', 'failureCount', 'headers', 'id', 'lastDeliveryAt', 'lastStatus', 'name', 'secret', 'updatedAt', 'url'] as const
  $columns = WebhookSchema.$columns
  @column({ consume: (value: unknown) => Boolean(value) })
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare eventFilters: any
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare events: any
  @column()
  declare failureCount: number
  @column({ prepare: (value: unknown) => JSON.stringify(value ?? null), consume: (value: unknown) => { if (typeof value !== 'string') return value; try { return JSON.parse(value) } catch { return null } } })
  declare headers: any
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastDeliveryAt: DateTime | null
  @column()
  declare lastStatus: string | null
  @column()
  declare name: string
  @column()
  declare secret: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
}
