/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type AuditLogTransformer from '#transformers/audit_log_transformer'
import type BlockTypeTransformer from '#transformers/block_type_transformer'
import type CollectionTransformer from '#transformers/collection_transformer'
import type EntryTransformer from '#transformers/entry_transformer'
import type EntryVersionTransformer from '#transformers/entry_version_transformer'
import type GlobalTransformer from '#transformers/global_transformer'
import type PageTransformer from '#transformers/page_transformer'
import type PageVersionTransformer from '#transformers/page_version_transformer'
import type RedirectTransformer from '#transformers/redirect_transformer'
import type RoleTransformer from '#transformers/role_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type AuditLog = InferData<AuditLogTransformer>
  export namespace AuditLog {
    export type Variants = InferVariants<AuditLogTransformer>
  }
  export type BlockType = InferData<BlockTypeTransformer>
  export namespace BlockType {
    export type Variants = InferVariants<BlockTypeTransformer>
  }
  export type Collection = InferData<CollectionTransformer>
  export namespace Collection {
    export type Variants = InferVariants<CollectionTransformer>
  }
  export type Entry = InferData<EntryTransformer>
  export namespace Entry {
    export type Variants = InferVariants<EntryTransformer>
  }
  export type EntryVersion = InferData<EntryVersionTransformer>
  export namespace EntryVersion {
    export type Variants = InferVariants<EntryVersionTransformer>
  }
  export type Global = InferData<GlobalTransformer>
  export namespace Global {
    export type Variants = InferVariants<GlobalTransformer>
  }
  export type Page = InferData<PageTransformer>
  export namespace Page {
    export type Variants = InferVariants<PageTransformer>
  }
  export type PageVersion = InferData<PageVersionTransformer>
  export namespace PageVersion {
    export type Variants = InferVariants<PageVersionTransformer>
  }
  export type Redirect = InferData<RedirectTransformer>
  export namespace Redirect {
    export type Variants = InferVariants<RedirectTransformer>
  }
  export type Role = InferData<RoleTransformer>
  export namespace Role {
    export type Variants = InferVariants<RoleTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
