/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'drive.fs.serve': {
    methods: ["GET","HEAD"],
    pattern: '/uploads/*',
    tokens: [{"old":"/uploads/*","type":0,"val":"uploads","end":""},{"old":"/uploads/*","type":2,"val":"*","end":""}],
    types: placeholder as Registry['drive.fs.serve']['types'],
  },
  'session.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/login',
    tokens: [{"old":"/admin/login","type":0,"val":"admin","end":""},{"old":"/admin/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.create']['types'],
  },
  'session.store': {
    methods: ["POST"],
    pattern: '/admin/login',
    tokens: [{"old":"/admin/login","type":0,"val":"admin","end":""},{"old":"/admin/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['session.store']['types'],
  },
  'session.challenge': {
    methods: ["GET","HEAD"],
    pattern: '/admin/login/challenge',
    tokens: [{"old":"/admin/login/challenge","type":0,"val":"admin","end":""},{"old":"/admin/login/challenge","type":0,"val":"login","end":""},{"old":"/admin/login/challenge","type":0,"val":"challenge","end":""}],
    types: placeholder as Registry['session.challenge']['types'],
  },
  'session.verify': {
    methods: ["POST"],
    pattern: '/admin/login/challenge',
    tokens: [{"old":"/admin/login/challenge","type":0,"val":"admin","end":""},{"old":"/admin/login/challenge","type":0,"val":"login","end":""},{"old":"/admin/login/challenge","type":0,"val":"challenge","end":""}],
    types: placeholder as Registry['session.verify']['types'],
  },
  'session.cancel': {
    methods: ["POST"],
    pattern: '/admin/login/cancel',
    tokens: [{"old":"/admin/login/cancel","type":0,"val":"admin","end":""},{"old":"/admin/login/cancel","type":0,"val":"login","end":""},{"old":"/admin/login/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['session.cancel']['types'],
  },
  'signup.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/signup',
    tokens: [{"old":"/admin/signup","type":0,"val":"admin","end":""},{"old":"/admin/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['signup.create']['types'],
  },
  'signup.store': {
    methods: ["POST"],
    pattern: '/admin/signup',
    tokens: [{"old":"/admin/signup","type":0,"val":"admin","end":""},{"old":"/admin/signup","type":0,"val":"signup","end":""}],
    types: placeholder as Registry['signup.store']['types'],
  },
  'password_reset.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/password-reset',
    tokens: [{"old":"/admin/password-reset","type":0,"val":"admin","end":""},{"old":"/admin/password-reset","type":0,"val":"password-reset","end":""}],
    types: placeholder as Registry['password_reset.create']['types'],
  },
  'password_reset.store': {
    methods: ["POST"],
    pattern: '/admin/password-reset',
    tokens: [{"old":"/admin/password-reset","type":0,"val":"admin","end":""},{"old":"/admin/password-reset","type":0,"val":"password-reset","end":""}],
    types: placeholder as Registry['password_reset.store']['types'],
  },
  'password_reset.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/password-reset/:token',
    tokens: [{"old":"/admin/password-reset/:token","type":0,"val":"admin","end":""},{"old":"/admin/password-reset/:token","type":0,"val":"password-reset","end":""},{"old":"/admin/password-reset/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['password_reset.edit']['types'],
  },
  'password_reset.update': {
    methods: ["PUT"],
    pattern: '/admin/password-reset/:token',
    tokens: [{"old":"/admin/password-reset/:token","type":0,"val":"admin","end":""},{"old":"/admin/password-reset/:token","type":0,"val":"password-reset","end":""},{"old":"/admin/password-reset/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['password_reset.update']['types'],
  },
  'email_verification.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/email-verification/:token',
    tokens: [{"old":"/admin/email-verification/:token","type":0,"val":"admin","end":""},{"old":"/admin/email-verification/:token","type":0,"val":"email-verification","end":""},{"old":"/admin/email-verification/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['email_verification.show']['types'],
  },
  'admin.session.destroy': {
    methods: ["POST"],
    pattern: '/admin/logout',
    tokens: [{"old":"/admin/logout","type":0,"val":"admin","end":""},{"old":"/admin/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['admin.session.destroy']['types'],
  },
  'admin.dashboard.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin',
    tokens: [{"old":"/admin","type":0,"val":"admin","end":""}],
    types: placeholder as Registry['admin.dashboard.show']['types'],
  },
  'admin.pages.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/pages',
    tokens: [{"old":"/admin/pages","type":0,"val":"admin","end":""},{"old":"/admin/pages","type":0,"val":"pages","end":""}],
    types: placeholder as Registry['admin.pages.index']['types'],
  },
  'admin.pages.bulk': {
    methods: ["POST"],
    pattern: '/admin/pages/bulk',
    tokens: [{"old":"/admin/pages/bulk","type":0,"val":"admin","end":""},{"old":"/admin/pages/bulk","type":0,"val":"pages","end":""},{"old":"/admin/pages/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin.pages.bulk']['types'],
  },
  'admin.pages.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/pages/new',
    tokens: [{"old":"/admin/pages/new","type":0,"val":"admin","end":""},{"old":"/admin/pages/new","type":0,"val":"pages","end":""},{"old":"/admin/pages/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['admin.pages.create']['types'],
  },
  'admin.pages.store': {
    methods: ["POST"],
    pattern: '/admin/pages',
    tokens: [{"old":"/admin/pages","type":0,"val":"admin","end":""},{"old":"/admin/pages","type":0,"val":"pages","end":""}],
    types: placeholder as Registry['admin.pages.store']['types'],
  },
  'admin.pages.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/pages/:id/edit',
    tokens: [{"old":"/admin/pages/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/edit","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.pages.edit']['types'],
  },
  'admin.pages.update': {
    methods: ["PUT"],
    pattern: '/admin/pages/:id',
    tokens: [{"old":"/admin/pages/:id","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.pages.update']['types'],
  },
  'admin.pages.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/pages/:id',
    tokens: [{"old":"/admin/pages/:id","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.pages.destroy']['types'],
  },
  'admin.page_publications.store': {
    methods: ["POST"],
    pattern: '/admin/pages/:id/publication',
    tokens: [{"old":"/admin/pages/:id/publication","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/publication","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/publication","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/publication","type":0,"val":"publication","end":""}],
    types: placeholder as Registry['admin.page_publications.store']['types'],
  },
  'admin.page_publications.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/pages/:id/publication',
    tokens: [{"old":"/admin/pages/:id/publication","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/publication","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/publication","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/publication","type":0,"val":"publication","end":""}],
    types: placeholder as Registry['admin.page_publications.destroy']['types'],
  },
  'admin.page_versions.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/pages/:id/versions',
    tokens: [{"old":"/admin/pages/:id/versions","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/versions","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/versions","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/versions","type":0,"val":"versions","end":""}],
    types: placeholder as Registry['admin.page_versions.index']['types'],
  },
  'admin.page_versions.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/pages/:id/versions/:versionId',
    tokens: [{"old":"/admin/pages/:id/versions/:versionId","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/versions/:versionId","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/versions/:versionId","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/versions/:versionId","type":0,"val":"versions","end":""},{"old":"/admin/pages/:id/versions/:versionId","type":1,"val":"versionId","end":""}],
    types: placeholder as Registry['admin.page_versions.show']['types'],
  },
  'admin.page_versions.restore': {
    methods: ["POST"],
    pattern: '/admin/pages/:id/versions/:versionId/restore',
    tokens: [{"old":"/admin/pages/:id/versions/:versionId/restore","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/versions/:versionId/restore","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/versions/:versionId/restore","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/versions/:versionId/restore","type":0,"val":"versions","end":""},{"old":"/admin/pages/:id/versions/:versionId/restore","type":1,"val":"versionId","end":""},{"old":"/admin/pages/:id/versions/:versionId/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['admin.page_versions.restore']['types'],
  },
  'admin.previews.page': {
    methods: ["GET","HEAD"],
    pattern: '/admin/pages/:id/preview',
    tokens: [{"old":"/admin/pages/:id/preview","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/preview","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/preview","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/preview","type":0,"val":"preview","end":""}],
    types: placeholder as Registry['admin.previews.page']['types'],
  },
  'admin.page_fields.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/pages/:id/fields',
    tokens: [{"old":"/admin/pages/:id/fields","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/fields","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/fields","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/fields","type":0,"val":"fields","end":""}],
    types: placeholder as Registry['admin.page_fields.show']['types'],
  },
  'admin.page_fields.update': {
    methods: ["PUT"],
    pattern: '/admin/pages/:id/fields',
    tokens: [{"old":"/admin/pages/:id/fields","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/fields","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/fields","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/fields","type":0,"val":"fields","end":""}],
    types: placeholder as Registry['admin.page_fields.update']['types'],
  },
  'admin.translations.page': {
    methods: ["POST"],
    pattern: '/admin/pages/:id/translations',
    tokens: [{"old":"/admin/pages/:id/translations","type":0,"val":"admin","end":""},{"old":"/admin/pages/:id/translations","type":0,"val":"pages","end":""},{"old":"/admin/pages/:id/translations","type":1,"val":"id","end":""},{"old":"/admin/pages/:id/translations","type":0,"val":"translations","end":""}],
    types: placeholder as Registry['admin.translations.page']['types'],
  },
  'admin.taxonomy_pools.pages': {
    methods: ["POST"],
    pattern: '/admin/pages/taxonomy-pools',
    tokens: [{"old":"/admin/pages/taxonomy-pools","type":0,"val":"admin","end":""},{"old":"/admin/pages/taxonomy-pools","type":0,"val":"pages","end":""},{"old":"/admin/pages/taxonomy-pools","type":0,"val":"taxonomy-pools","end":""}],
    types: placeholder as Registry['admin.taxonomy_pools.pages']['types'],
  },
  'admin.translations.entry': {
    methods: ["POST"],
    pattern: '/admin/collections/:collectionId/entries/:id/translations',
    tokens: [{"old":"/admin/collections/:collectionId/entries/:id/translations","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/:id/translations","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/:id/translations","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/:id/translations","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/:id/translations","type":1,"val":"id","end":""},{"old":"/admin/collections/:collectionId/entries/:id/translations","type":0,"val":"translations","end":""}],
    types: placeholder as Registry['admin.translations.entry']['types'],
  },
  'admin.collections.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/collections',
    tokens: [{"old":"/admin/collections","type":0,"val":"admin","end":""},{"old":"/admin/collections","type":0,"val":"collections","end":""}],
    types: placeholder as Registry['admin.collections.index']['types'],
  },
  'admin.collections.bulk': {
    methods: ["POST"],
    pattern: '/admin/collections/bulk',
    tokens: [{"old":"/admin/collections/bulk","type":0,"val":"admin","end":""},{"old":"/admin/collections/bulk","type":0,"val":"collections","end":""},{"old":"/admin/collections/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin.collections.bulk']['types'],
  },
  'admin.collections.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/collections/new',
    tokens: [{"old":"/admin/collections/new","type":0,"val":"admin","end":""},{"old":"/admin/collections/new","type":0,"val":"collections","end":""},{"old":"/admin/collections/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['admin.collections.create']['types'],
  },
  'admin.collections.store': {
    methods: ["POST"],
    pattern: '/admin/collections',
    tokens: [{"old":"/admin/collections","type":0,"val":"admin","end":""},{"old":"/admin/collections","type":0,"val":"collections","end":""}],
    types: placeholder as Registry['admin.collections.store']['types'],
  },
  'admin.collections.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/collections/:id/edit',
    tokens: [{"old":"/admin/collections/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/collections/:id/edit","type":0,"val":"collections","end":""},{"old":"/admin/collections/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/collections/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.collections.edit']['types'],
  },
  'admin.collections.update': {
    methods: ["PUT"],
    pattern: '/admin/collections/:id',
    tokens: [{"old":"/admin/collections/:id","type":0,"val":"admin","end":""},{"old":"/admin/collections/:id","type":0,"val":"collections","end":""},{"old":"/admin/collections/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.collections.update']['types'],
  },
  'admin.collections.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/collections/:id',
    tokens: [{"old":"/admin/collections/:id","type":0,"val":"admin","end":""},{"old":"/admin/collections/:id","type":0,"val":"collections","end":""},{"old":"/admin/collections/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.collections.destroy']['types'],
  },
  'admin.entries.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/collections/:collectionId/entries',
    tokens: [{"old":"/admin/collections/:collectionId/entries","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries","type":0,"val":"entries","end":""}],
    types: placeholder as Registry['admin.entries.index']['types'],
  },
  'admin.entries.bulk': {
    methods: ["POST"],
    pattern: '/admin/collections/:collectionId/entries/bulk',
    tokens: [{"old":"/admin/collections/:collectionId/entries/bulk","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/bulk","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/bulk","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/bulk","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin.entries.bulk']['types'],
  },
  'admin.entries.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/collections/:collectionId/entries/new',
    tokens: [{"old":"/admin/collections/:collectionId/entries/new","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/new","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/new","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/new","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['admin.entries.create']['types'],
  },
  'admin.entries.store': {
    methods: ["POST"],
    pattern: '/admin/collections/:collectionId/entries',
    tokens: [{"old":"/admin/collections/:collectionId/entries","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries","type":0,"val":"entries","end":""}],
    types: placeholder as Registry['admin.entries.store']['types'],
  },
  'admin.entries.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/collections/:collectionId/entries/:id/edit',
    tokens: [{"old":"/admin/collections/:collectionId/entries/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/:id/edit","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/:id/edit","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/:id/edit","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/collections/:collectionId/entries/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.entries.edit']['types'],
  },
  'admin.entries.update': {
    methods: ["PUT"],
    pattern: '/admin/collections/:collectionId/entries/:id',
    tokens: [{"old":"/admin/collections/:collectionId/entries/:id","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/:id","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/:id","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/:id","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.entries.update']['types'],
  },
  'admin.entries.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/collections/:collectionId/entries/:id',
    tokens: [{"old":"/admin/collections/:collectionId/entries/:id","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/:id","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/:id","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/:id","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.entries.destroy']['types'],
  },
  'admin.entry_publications.store': {
    methods: ["POST"],
    pattern: '/admin/collections/:collectionId/entries/:id/publication',
    tokens: [{"old":"/admin/collections/:collectionId/entries/:id/publication","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/:id/publication","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/:id/publication","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/:id/publication","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/:id/publication","type":1,"val":"id","end":""},{"old":"/admin/collections/:collectionId/entries/:id/publication","type":0,"val":"publication","end":""}],
    types: placeholder as Registry['admin.entry_publications.store']['types'],
  },
  'admin.entry_publications.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/collections/:collectionId/entries/:id/publication',
    tokens: [{"old":"/admin/collections/:collectionId/entries/:id/publication","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/:id/publication","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/:id/publication","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/:id/publication","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/:id/publication","type":1,"val":"id","end":""},{"old":"/admin/collections/:collectionId/entries/:id/publication","type":0,"val":"publication","end":""}],
    types: placeholder as Registry['admin.entry_publications.destroy']['types'],
  },
  'admin.entry_versions.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/collections/:collectionId/entries/:id/versions',
    tokens: [{"old":"/admin/collections/:collectionId/entries/:id/versions","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions","type":1,"val":"id","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions","type":0,"val":"versions","end":""}],
    types: placeholder as Registry['admin.entry_versions.index']['types'],
  },
  'admin.entry_versions.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/collections/:collectionId/entries/:id/versions/:versionId',
    tokens: [{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId","type":1,"val":"id","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId","type":0,"val":"versions","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId","type":1,"val":"versionId","end":""}],
    types: placeholder as Registry['admin.entry_versions.show']['types'],
  },
  'admin.entry_versions.restore': {
    methods: ["POST"],
    pattern: '/admin/collections/:collectionId/entries/:id/versions/:versionId/restore',
    tokens: [{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId/restore","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId/restore","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId/restore","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId/restore","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId/restore","type":1,"val":"id","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId/restore","type":0,"val":"versions","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId/restore","type":1,"val":"versionId","end":""},{"old":"/admin/collections/:collectionId/entries/:id/versions/:versionId/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['admin.entry_versions.restore']['types'],
  },
  'admin.previews.entry': {
    methods: ["GET","HEAD"],
    pattern: '/admin/collections/:collectionId/entries/:id/preview',
    tokens: [{"old":"/admin/collections/:collectionId/entries/:id/preview","type":0,"val":"admin","end":""},{"old":"/admin/collections/:collectionId/entries/:id/preview","type":0,"val":"collections","end":""},{"old":"/admin/collections/:collectionId/entries/:id/preview","type":1,"val":"collectionId","end":""},{"old":"/admin/collections/:collectionId/entries/:id/preview","type":0,"val":"entries","end":""},{"old":"/admin/collections/:collectionId/entries/:id/preview","type":1,"val":"id","end":""},{"old":"/admin/collections/:collectionId/entries/:id/preview","type":0,"val":"preview","end":""}],
    types: placeholder as Registry['admin.previews.entry']['types'],
  },
  'admin.globals.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/globals',
    tokens: [{"old":"/admin/globals","type":0,"val":"admin","end":""},{"old":"/admin/globals","type":0,"val":"globals","end":""}],
    types: placeholder as Registry['admin.globals.index']['types'],
  },
  'admin.globals.bulk': {
    methods: ["POST"],
    pattern: '/admin/globals/bulk',
    tokens: [{"old":"/admin/globals/bulk","type":0,"val":"admin","end":""},{"old":"/admin/globals/bulk","type":0,"val":"globals","end":""},{"old":"/admin/globals/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin.globals.bulk']['types'],
  },
  'admin.globals.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/globals/new',
    tokens: [{"old":"/admin/globals/new","type":0,"val":"admin","end":""},{"old":"/admin/globals/new","type":0,"val":"globals","end":""},{"old":"/admin/globals/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['admin.globals.create']['types'],
  },
  'admin.globals.store': {
    methods: ["POST"],
    pattern: '/admin/globals',
    tokens: [{"old":"/admin/globals","type":0,"val":"admin","end":""},{"old":"/admin/globals","type":0,"val":"globals","end":""}],
    types: placeholder as Registry['admin.globals.store']['types'],
  },
  'admin.globals.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/globals/:id/edit',
    tokens: [{"old":"/admin/globals/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/globals/:id/edit","type":0,"val":"globals","end":""},{"old":"/admin/globals/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/globals/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.globals.edit']['types'],
  },
  'admin.globals.update': {
    methods: ["PUT"],
    pattern: '/admin/globals/:id',
    tokens: [{"old":"/admin/globals/:id","type":0,"val":"admin","end":""},{"old":"/admin/globals/:id","type":0,"val":"globals","end":""},{"old":"/admin/globals/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.globals.update']['types'],
  },
  'admin.globals.update_fields': {
    methods: ["PUT"],
    pattern: '/admin/globals/:id/fields',
    tokens: [{"old":"/admin/globals/:id/fields","type":0,"val":"admin","end":""},{"old":"/admin/globals/:id/fields","type":0,"val":"globals","end":""},{"old":"/admin/globals/:id/fields","type":1,"val":"id","end":""},{"old":"/admin/globals/:id/fields","type":0,"val":"fields","end":""}],
    types: placeholder as Registry['admin.globals.update_fields']['types'],
  },
  'admin.globals.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/globals/:id',
    tokens: [{"old":"/admin/globals/:id","type":0,"val":"admin","end":""},{"old":"/admin/globals/:id","type":0,"val":"globals","end":""},{"old":"/admin/globals/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.globals.destroy']['types'],
  },
  'admin.block_types.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/block-types',
    tokens: [{"old":"/admin/block-types","type":0,"val":"admin","end":""},{"old":"/admin/block-types","type":0,"val":"block-types","end":""}],
    types: placeholder as Registry['admin.block_types.index']['types'],
  },
  'admin.block_types.bulk': {
    methods: ["POST"],
    pattern: '/admin/block-types/bulk',
    tokens: [{"old":"/admin/block-types/bulk","type":0,"val":"admin","end":""},{"old":"/admin/block-types/bulk","type":0,"val":"block-types","end":""},{"old":"/admin/block-types/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin.block_types.bulk']['types'],
  },
  'admin.block_types.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/block-types/new',
    tokens: [{"old":"/admin/block-types/new","type":0,"val":"admin","end":""},{"old":"/admin/block-types/new","type":0,"val":"block-types","end":""},{"old":"/admin/block-types/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['admin.block_types.create']['types'],
  },
  'admin.block_types.store': {
    methods: ["POST"],
    pattern: '/admin/block-types',
    tokens: [{"old":"/admin/block-types","type":0,"val":"admin","end":""},{"old":"/admin/block-types","type":0,"val":"block-types","end":""}],
    types: placeholder as Registry['admin.block_types.store']['types'],
  },
  'admin.block_types.seed': {
    methods: ["POST"],
    pattern: '/admin/block-types/seed',
    tokens: [{"old":"/admin/block-types/seed","type":0,"val":"admin","end":""},{"old":"/admin/block-types/seed","type":0,"val":"block-types","end":""},{"old":"/admin/block-types/seed","type":0,"val":"seed","end":""}],
    types: placeholder as Registry['admin.block_types.seed']['types'],
  },
  'admin.block_types.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/block-types/:id/edit',
    tokens: [{"old":"/admin/block-types/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/block-types/:id/edit","type":0,"val":"block-types","end":""},{"old":"/admin/block-types/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/block-types/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.block_types.edit']['types'],
  },
  'admin.block_types.update': {
    methods: ["PUT"],
    pattern: '/admin/block-types/:id',
    tokens: [{"old":"/admin/block-types/:id","type":0,"val":"admin","end":""},{"old":"/admin/block-types/:id","type":0,"val":"block-types","end":""},{"old":"/admin/block-types/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.block_types.update']['types'],
  },
  'admin.block_types.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/block-types/:id',
    tokens: [{"old":"/admin/block-types/:id","type":0,"val":"admin","end":""},{"old":"/admin/block-types/:id","type":0,"val":"block-types","end":""},{"old":"/admin/block-types/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.block_types.destroy']['types'],
  },
  'admin.lookups.pages': {
    methods: ["GET","HEAD"],
    pattern: '/admin/lookups/pages',
    tokens: [{"old":"/admin/lookups/pages","type":0,"val":"admin","end":""},{"old":"/admin/lookups/pages","type":0,"val":"lookups","end":""},{"old":"/admin/lookups/pages","type":0,"val":"pages","end":""}],
    types: placeholder as Registry['admin.lookups.pages']['types'],
  },
  'admin.lookups.entries': {
    methods: ["GET","HEAD"],
    pattern: '/admin/lookups/entries',
    tokens: [{"old":"/admin/lookups/entries","type":0,"val":"admin","end":""},{"old":"/admin/lookups/entries","type":0,"val":"lookups","end":""},{"old":"/admin/lookups/entries","type":0,"val":"entries","end":""}],
    types: placeholder as Registry['admin.lookups.entries']['types'],
  },
  'admin.markdown_previews.store': {
    methods: ["POST"],
    pattern: '/admin/markdown-preview',
    tokens: [{"old":"/admin/markdown-preview","type":0,"val":"admin","end":""},{"old":"/admin/markdown-preview","type":0,"val":"markdown-preview","end":""}],
    types: placeholder as Registry['admin.markdown_previews.store']['types'],
  },
  'admin.redirects.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/redirects',
    tokens: [{"old":"/admin/redirects","type":0,"val":"admin","end":""},{"old":"/admin/redirects","type":0,"val":"redirects","end":""}],
    types: placeholder as Registry['admin.redirects.index']['types'],
  },
  'admin.redirects.bulk': {
    methods: ["POST"],
    pattern: '/admin/redirects/bulk',
    tokens: [{"old":"/admin/redirects/bulk","type":0,"val":"admin","end":""},{"old":"/admin/redirects/bulk","type":0,"val":"redirects","end":""},{"old":"/admin/redirects/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin.redirects.bulk']['types'],
  },
  'admin.redirects.store': {
    methods: ["POST"],
    pattern: '/admin/redirects',
    tokens: [{"old":"/admin/redirects","type":0,"val":"admin","end":""},{"old":"/admin/redirects","type":0,"val":"redirects","end":""}],
    types: placeholder as Registry['admin.redirects.store']['types'],
  },
  'admin.redirects.update': {
    methods: ["PUT"],
    pattern: '/admin/redirects/:id',
    tokens: [{"old":"/admin/redirects/:id","type":0,"val":"admin","end":""},{"old":"/admin/redirects/:id","type":0,"val":"redirects","end":""},{"old":"/admin/redirects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.redirects.update']['types'],
  },
  'admin.redirects.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/redirects/:id',
    tokens: [{"old":"/admin/redirects/:id","type":0,"val":"admin","end":""},{"old":"/admin/redirects/:id","type":0,"val":"redirects","end":""},{"old":"/admin/redirects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.redirects.destroy']['types'],
  },
  'admin.users.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.users.index']['types'],
  },
  'admin.users.bulk': {
    methods: ["POST"],
    pattern: '/admin/users/bulk',
    tokens: [{"old":"/admin/users/bulk","type":0,"val":"admin","end":""},{"old":"/admin/users/bulk","type":0,"val":"users","end":""},{"old":"/admin/users/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin.users.bulk']['types'],
  },
  'admin.users.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/new',
    tokens: [{"old":"/admin/users/new","type":0,"val":"admin","end":""},{"old":"/admin/users/new","type":0,"val":"users","end":""},{"old":"/admin/users/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['admin.users.create']['types'],
  },
  'admin.users.store': {
    methods: ["POST"],
    pattern: '/admin/users',
    tokens: [{"old":"/admin/users","type":0,"val":"admin","end":""},{"old":"/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.users.store']['types'],
  },
  'admin.users.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/users/:id/edit',
    tokens: [{"old":"/admin/users/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/users/:id/edit","type":0,"val":"users","end":""},{"old":"/admin/users/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/users/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.users.edit']['types'],
  },
  'admin.users.update': {
    methods: ["PUT"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users.update']['types'],
  },
  'admin.users.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/users/:id',
    tokens: [{"old":"/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/admin/users/:id","type":0,"val":"users","end":""},{"old":"/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.users.destroy']['types'],
  },
  'admin.roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles',
    tokens: [{"old":"/admin/roles","type":0,"val":"admin","end":""},{"old":"/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['admin.roles.index']['types'],
  },
  'admin.roles.bulk': {
    methods: ["POST"],
    pattern: '/admin/roles/bulk',
    tokens: [{"old":"/admin/roles/bulk","type":0,"val":"admin","end":""},{"old":"/admin/roles/bulk","type":0,"val":"roles","end":""},{"old":"/admin/roles/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin.roles.bulk']['types'],
  },
  'admin.roles.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/new',
    tokens: [{"old":"/admin/roles/new","type":0,"val":"admin","end":""},{"old":"/admin/roles/new","type":0,"val":"roles","end":""},{"old":"/admin/roles/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['admin.roles.create']['types'],
  },
  'admin.roles.store': {
    methods: ["POST"],
    pattern: '/admin/roles',
    tokens: [{"old":"/admin/roles","type":0,"val":"admin","end":""},{"old":"/admin/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['admin.roles.store']['types'],
  },
  'admin.roles.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/roles/:id/edit',
    tokens: [{"old":"/admin/roles/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/roles/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.roles.edit']['types'],
  },
  'admin.roles.update': {
    methods: ["PUT"],
    pattern: '/admin/roles/:id',
    tokens: [{"old":"/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.roles.update']['types'],
  },
  'admin.roles.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/roles/:id',
    tokens: [{"old":"/admin/roles/:id","type":0,"val":"admin","end":""},{"old":"/admin/roles/:id","type":0,"val":"roles","end":""},{"old":"/admin/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.roles.destroy']['types'],
  },
  'admin.api_tokens.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings/api-token',
    tokens: [{"old":"/admin/settings/api-token","type":0,"val":"admin","end":""},{"old":"/admin/settings/api-token","type":0,"val":"settings","end":""},{"old":"/admin/settings/api-token","type":0,"val":"api-token","end":""}],
    types: placeholder as Registry['admin.api_tokens.show']['types'],
  },
  'admin.api_tokens.reveal': {
    methods: ["POST"],
    pattern: '/admin/settings/api-token/reveal',
    tokens: [{"old":"/admin/settings/api-token/reveal","type":0,"val":"admin","end":""},{"old":"/admin/settings/api-token/reveal","type":0,"val":"settings","end":""},{"old":"/admin/settings/api-token/reveal","type":0,"val":"api-token","end":""},{"old":"/admin/settings/api-token/reveal","type":0,"val":"reveal","end":""}],
    types: placeholder as Registry['admin.api_tokens.reveal']['types'],
  },
  'admin.api_tokens.rotate': {
    methods: ["POST"],
    pattern: '/admin/settings/api-token/rotate',
    tokens: [{"old":"/admin/settings/api-token/rotate","type":0,"val":"admin","end":""},{"old":"/admin/settings/api-token/rotate","type":0,"val":"settings","end":""},{"old":"/admin/settings/api-token/rotate","type":0,"val":"api-token","end":""},{"old":"/admin/settings/api-token/rotate","type":0,"val":"rotate","end":""}],
    types: placeholder as Registry['admin.api_tokens.rotate']['types'],
  },
  'admin.service_tokens.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings/service-tokens',
    tokens: [{"old":"/admin/settings/service-tokens","type":0,"val":"admin","end":""},{"old":"/admin/settings/service-tokens","type":0,"val":"settings","end":""},{"old":"/admin/settings/service-tokens","type":0,"val":"service-tokens","end":""}],
    types: placeholder as Registry['admin.service_tokens.index']['types'],
  },
  'admin.service_tokens.store': {
    methods: ["POST"],
    pattern: '/admin/settings/service-tokens',
    tokens: [{"old":"/admin/settings/service-tokens","type":0,"val":"admin","end":""},{"old":"/admin/settings/service-tokens","type":0,"val":"settings","end":""},{"old":"/admin/settings/service-tokens","type":0,"val":"service-tokens","end":""}],
    types: placeholder as Registry['admin.service_tokens.store']['types'],
  },
  'admin.service_tokens.reveal': {
    methods: ["POST"],
    pattern: '/admin/settings/service-tokens/:id/reveal',
    tokens: [{"old":"/admin/settings/service-tokens/:id/reveal","type":0,"val":"admin","end":""},{"old":"/admin/settings/service-tokens/:id/reveal","type":0,"val":"settings","end":""},{"old":"/admin/settings/service-tokens/:id/reveal","type":0,"val":"service-tokens","end":""},{"old":"/admin/settings/service-tokens/:id/reveal","type":1,"val":"id","end":""},{"old":"/admin/settings/service-tokens/:id/reveal","type":0,"val":"reveal","end":""}],
    types: placeholder as Registry['admin.service_tokens.reveal']['types'],
  },
  'admin.service_tokens.rotate': {
    methods: ["POST"],
    pattern: '/admin/settings/service-tokens/:id/rotate',
    tokens: [{"old":"/admin/settings/service-tokens/:id/rotate","type":0,"val":"admin","end":""},{"old":"/admin/settings/service-tokens/:id/rotate","type":0,"val":"settings","end":""},{"old":"/admin/settings/service-tokens/:id/rotate","type":0,"val":"service-tokens","end":""},{"old":"/admin/settings/service-tokens/:id/rotate","type":1,"val":"id","end":""},{"old":"/admin/settings/service-tokens/:id/rotate","type":0,"val":"rotate","end":""}],
    types: placeholder as Registry['admin.service_tokens.rotate']['types'],
  },
  'admin.service_tokens.revoke': {
    methods: ["POST"],
    pattern: '/admin/settings/service-tokens/:id/revoke',
    tokens: [{"old":"/admin/settings/service-tokens/:id/revoke","type":0,"val":"admin","end":""},{"old":"/admin/settings/service-tokens/:id/revoke","type":0,"val":"settings","end":""},{"old":"/admin/settings/service-tokens/:id/revoke","type":0,"val":"service-tokens","end":""},{"old":"/admin/settings/service-tokens/:id/revoke","type":1,"val":"id","end":""},{"old":"/admin/settings/service-tokens/:id/revoke","type":0,"val":"revoke","end":""}],
    types: placeholder as Registry['admin.service_tokens.revoke']['types'],
  },
  'admin.api_clients.legacy': {
    methods: ["GET","HEAD"],
    pattern: '/admin/api-clients',
    tokens: [{"old":"/admin/api-clients","type":0,"val":"admin","end":""},{"old":"/admin/api-clients","type":0,"val":"api-clients","end":""}],
    types: placeholder as Registry['admin.api_clients.legacy']['types'],
  },
  'admin.settings.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings',
    tokens: [{"old":"/admin/settings","type":0,"val":"admin","end":""},{"old":"/admin/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['admin.settings.edit']['types'],
  },
  'admin.settings.update': {
    methods: ["PUT"],
    pattern: '/admin/settings',
    tokens: [{"old":"/admin/settings","type":0,"val":"admin","end":""},{"old":"/admin/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['admin.settings.update']['types'],
  },
  'admin.general_settings.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings/general',
    tokens: [{"old":"/admin/settings/general","type":0,"val":"admin","end":""},{"old":"/admin/settings/general","type":0,"val":"settings","end":""},{"old":"/admin/settings/general","type":0,"val":"general","end":""}],
    types: placeholder as Registry['admin.general_settings.edit']['types'],
  },
  'admin.general_settings.update': {
    methods: ["PUT"],
    pattern: '/admin/settings/general',
    tokens: [{"old":"/admin/settings/general","type":0,"val":"admin","end":""},{"old":"/admin/settings/general","type":0,"val":"settings","end":""},{"old":"/admin/settings/general","type":0,"val":"general","end":""}],
    types: placeholder as Registry['admin.general_settings.update']['types'],
  },
  'admin.branding.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings/branding',
    tokens: [{"old":"/admin/settings/branding","type":0,"val":"admin","end":""},{"old":"/admin/settings/branding","type":0,"val":"settings","end":""},{"old":"/admin/settings/branding","type":0,"val":"branding","end":""}],
    types: placeholder as Registry['admin.branding.edit']['types'],
  },
  'admin.branding.update': {
    methods: ["PUT"],
    pattern: '/admin/settings/branding',
    tokens: [{"old":"/admin/settings/branding","type":0,"val":"admin","end":""},{"old":"/admin/settings/branding","type":0,"val":"settings","end":""},{"old":"/admin/settings/branding","type":0,"val":"branding","end":""}],
    types: placeholder as Registry['admin.branding.update']['types'],
  },
  'admin.languages_settings.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings/languages',
    tokens: [{"old":"/admin/settings/languages","type":0,"val":"admin","end":""},{"old":"/admin/settings/languages","type":0,"val":"settings","end":""},{"old":"/admin/settings/languages","type":0,"val":"languages","end":""}],
    types: placeholder as Registry['admin.languages_settings.edit']['types'],
  },
  'admin.languages_settings.update': {
    methods: ["PUT"],
    pattern: '/admin/settings/languages',
    tokens: [{"old":"/admin/settings/languages","type":0,"val":"admin","end":""},{"old":"/admin/settings/languages","type":0,"val":"settings","end":""},{"old":"/admin/settings/languages","type":0,"val":"languages","end":""}],
    types: placeholder as Registry['admin.languages_settings.update']['types'],
  },
  'admin.brand_brief.update': {
    methods: ["PUT"],
    pattern: '/admin/settings/brand',
    tokens: [{"old":"/admin/settings/brand","type":0,"val":"admin","end":""},{"old":"/admin/settings/brand","type":0,"val":"settings","end":""},{"old":"/admin/settings/brand","type":0,"val":"brand","end":""}],
    types: placeholder as Registry['admin.brand_brief.update']['types'],
  },
  'admin.account.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/account',
    tokens: [{"old":"/admin/account","type":0,"val":"admin","end":""},{"old":"/admin/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['admin.account.edit']['types'],
  },
  'admin.account.update': {
    methods: ["PUT"],
    pattern: '/admin/account',
    tokens: [{"old":"/admin/account","type":0,"val":"admin","end":""},{"old":"/admin/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['admin.account.update']['types'],
  },
  'admin.account.email': {
    methods: ["PUT"],
    pattern: '/admin/account/email',
    tokens: [{"old":"/admin/account/email","type":0,"val":"admin","end":""},{"old":"/admin/account/email","type":0,"val":"account","end":""},{"old":"/admin/account/email","type":0,"val":"email","end":""}],
    types: placeholder as Registry['admin.account.email']['types'],
  },
  'admin.account.password': {
    methods: ["PUT"],
    pattern: '/admin/account/password',
    tokens: [{"old":"/admin/account/password","type":0,"val":"admin","end":""},{"old":"/admin/account/password","type":0,"val":"account","end":""},{"old":"/admin/account/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['admin.account.password']['types'],
  },
  'admin.account.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/account',
    tokens: [{"old":"/admin/account","type":0,"val":"admin","end":""},{"old":"/admin/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['admin.account.destroy']['types'],
  },
  'admin.account.email_verification': {
    methods: ["POST"],
    pattern: '/admin/account/email-verification',
    tokens: [{"old":"/admin/account/email-verification","type":0,"val":"admin","end":""},{"old":"/admin/account/email-verification","type":0,"val":"account","end":""},{"old":"/admin/account/email-verification","type":0,"val":"email-verification","end":""}],
    types: placeholder as Registry['admin.account.email_verification']['types'],
  },
  'admin.two_factor.store': {
    methods: ["POST"],
    pattern: '/admin/account/two-factor',
    tokens: [{"old":"/admin/account/two-factor","type":0,"val":"admin","end":""},{"old":"/admin/account/two-factor","type":0,"val":"account","end":""},{"old":"/admin/account/two-factor","type":0,"val":"two-factor","end":""}],
    types: placeholder as Registry['admin.two_factor.store']['types'],
  },
  'admin.two_factor.regenerate': {
    methods: ["POST"],
    pattern: '/admin/account/two-factor/recovery-codes',
    tokens: [{"old":"/admin/account/two-factor/recovery-codes","type":0,"val":"admin","end":""},{"old":"/admin/account/two-factor/recovery-codes","type":0,"val":"account","end":""},{"old":"/admin/account/two-factor/recovery-codes","type":0,"val":"two-factor","end":""},{"old":"/admin/account/two-factor/recovery-codes","type":0,"val":"recovery-codes","end":""}],
    types: placeholder as Registry['admin.two_factor.regenerate']['types'],
  },
  'admin.two_factor.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/account/two-factor',
    tokens: [{"old":"/admin/account/two-factor","type":0,"val":"admin","end":""},{"old":"/admin/account/two-factor","type":0,"val":"account","end":""},{"old":"/admin/account/two-factor","type":0,"val":"two-factor","end":""}],
    types: placeholder as Registry['admin.two_factor.destroy']['types'],
  },
  'admin.account_sessions.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/account/sessions/:id',
    tokens: [{"old":"/admin/account/sessions/:id","type":0,"val":"admin","end":""},{"old":"/admin/account/sessions/:id","type":0,"val":"account","end":""},{"old":"/admin/account/sessions/:id","type":0,"val":"sessions","end":""},{"old":"/admin/account/sessions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.account_sessions.destroy']['types'],
  },
  'admin.plugins.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/plugins',
    tokens: [{"old":"/admin/plugins","type":0,"val":"admin","end":""},{"old":"/admin/plugins","type":0,"val":"plugins","end":""}],
    types: placeholder as Registry['admin.plugins.index']['types'],
  },
  'admin.plugins.update': {
    methods: ["PUT"],
    pattern: '/admin/plugins/:key',
    tokens: [{"old":"/admin/plugins/:key","type":0,"val":"admin","end":""},{"old":"/admin/plugins/:key","type":0,"val":"plugins","end":""},{"old":"/admin/plugins/:key","type":1,"val":"key","end":""}],
    types: placeholder as Registry['admin.plugins.update']['types'],
  },
  'admin.audit_logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/audit-log',
    tokens: [{"old":"/admin/audit-log","type":0,"val":"admin","end":""},{"old":"/admin/audit-log","type":0,"val":"audit-log","end":""}],
    types: placeholder as Registry['admin.audit_logs.index']['types'],
  },
  'admin.webhooks.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/webhooks',
    tokens: [{"old":"/admin/webhooks","type":0,"val":"admin","end":""},{"old":"/admin/webhooks","type":0,"val":"webhooks","end":""}],
    types: placeholder as Registry['admin.webhooks.index']['types'],
  },
  'admin.webhooks.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/webhooks/new',
    tokens: [{"old":"/admin/webhooks/new","type":0,"val":"admin","end":""},{"old":"/admin/webhooks/new","type":0,"val":"webhooks","end":""},{"old":"/admin/webhooks/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['admin.webhooks.create']['types'],
  },
  'admin.webhooks.store': {
    methods: ["POST"],
    pattern: '/admin/webhooks',
    tokens: [{"old":"/admin/webhooks","type":0,"val":"admin","end":""},{"old":"/admin/webhooks","type":0,"val":"webhooks","end":""}],
    types: placeholder as Registry['admin.webhooks.store']['types'],
  },
  'admin.webhooks.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/webhooks/:id/edit',
    tokens: [{"old":"/admin/webhooks/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/webhooks/:id/edit","type":0,"val":"webhooks","end":""},{"old":"/admin/webhooks/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/webhooks/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.webhooks.edit']['types'],
  },
  'admin.webhooks.update': {
    methods: ["PUT"],
    pattern: '/admin/webhooks/:id',
    tokens: [{"old":"/admin/webhooks/:id","type":0,"val":"admin","end":""},{"old":"/admin/webhooks/:id","type":0,"val":"webhooks","end":""},{"old":"/admin/webhooks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.webhooks.update']['types'],
  },
  'admin.webhooks.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/webhooks/:id',
    tokens: [{"old":"/admin/webhooks/:id","type":0,"val":"admin","end":""},{"old":"/admin/webhooks/:id","type":0,"val":"webhooks","end":""},{"old":"/admin/webhooks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.webhooks.destroy']['types'],
  },
  'admin.webhooks.rotate_secret': {
    methods: ["POST"],
    pattern: '/admin/webhooks/:id/secret',
    tokens: [{"old":"/admin/webhooks/:id/secret","type":0,"val":"admin","end":""},{"old":"/admin/webhooks/:id/secret","type":0,"val":"webhooks","end":""},{"old":"/admin/webhooks/:id/secret","type":1,"val":"id","end":""},{"old":"/admin/webhooks/:id/secret","type":0,"val":"secret","end":""}],
    types: placeholder as Registry['admin.webhooks.rotate_secret']['types'],
  },
  'admin.webhooks.test': {
    methods: ["POST"],
    pattern: '/admin/webhooks/:id/test',
    tokens: [{"old":"/admin/webhooks/:id/test","type":0,"val":"admin","end":""},{"old":"/admin/webhooks/:id/test","type":0,"val":"webhooks","end":""},{"old":"/admin/webhooks/:id/test","type":1,"val":"id","end":""},{"old":"/admin/webhooks/:id/test","type":0,"val":"test","end":""}],
    types: placeholder as Registry['admin.webhooks.test']['types'],
  },
  'admin.trash.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/trash',
    tokens: [{"old":"/admin/trash","type":0,"val":"admin","end":""},{"old":"/admin/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['admin.trash.index']['types'],
  },
  'admin.trash.bulk': {
    methods: ["POST"],
    pattern: '/admin/trash/bulk',
    tokens: [{"old":"/admin/trash/bulk","type":0,"val":"admin","end":""},{"old":"/admin/trash/bulk","type":0,"val":"trash","end":""},{"old":"/admin/trash/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin.trash.bulk']['types'],
  },
  'admin.trash.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/trash/:type/:id',
    tokens: [{"old":"/admin/trash/:type/:id","type":0,"val":"admin","end":""},{"old":"/admin/trash/:type/:id","type":0,"val":"trash","end":""},{"old":"/admin/trash/:type/:id","type":1,"val":"type","end":""},{"old":"/admin/trash/:type/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.trash.show']['types'],
  },
  'admin.trash.restore': {
    methods: ["POST"],
    pattern: '/admin/trash/:type/:id/restore',
    tokens: [{"old":"/admin/trash/:type/:id/restore","type":0,"val":"admin","end":""},{"old":"/admin/trash/:type/:id/restore","type":0,"val":"trash","end":""},{"old":"/admin/trash/:type/:id/restore","type":1,"val":"type","end":""},{"old":"/admin/trash/:type/:id/restore","type":1,"val":"id","end":""},{"old":"/admin/trash/:type/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['admin.trash.restore']['types'],
  },
  'admin.trash.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/trash/:type/:id',
    tokens: [{"old":"/admin/trash/:type/:id","type":0,"val":"admin","end":""},{"old":"/admin/trash/:type/:id","type":0,"val":"trash","end":""},{"old":"/admin/trash/:type/:id","type":1,"val":"type","end":""},{"old":"/admin/trash/:type/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.trash.destroy']['types'],
  },
  'api.site.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/site',
    tokens: [{"old":"/api/v1/site","type":0,"val":"api","end":""},{"old":"/api/v1/site","type":0,"val":"v1","end":""},{"old":"/api/v1/site","type":0,"val":"site","end":""}],
    types: placeholder as Registry['api.site.show']['types'],
  },
  'api.schema.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/schema',
    tokens: [{"old":"/api/v1/schema","type":0,"val":"api","end":""},{"old":"/api/v1/schema","type":0,"val":"v1","end":""},{"old":"/api/v1/schema","type":0,"val":"schema","end":""}],
    types: placeholder as Registry['api.schema.show']['types'],
  },
  'api.pages.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/pages',
    tokens: [{"old":"/api/v1/pages","type":0,"val":"api","end":""},{"old":"/api/v1/pages","type":0,"val":"v1","end":""},{"old":"/api/v1/pages","type":0,"val":"pages","end":""}],
    types: placeholder as Registry['api.pages.index']['types'],
  },
  'api.pages.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/pages/*',
    tokens: [{"old":"/api/v1/pages/*","type":0,"val":"api","end":""},{"old":"/api/v1/pages/*","type":0,"val":"v1","end":""},{"old":"/api/v1/pages/*","type":0,"val":"pages","end":""},{"old":"/api/v1/pages/*","type":2,"val":"*","end":""}],
    types: placeholder as Registry['api.pages.show']['types'],
  },
  'api.collections.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/collections',
    tokens: [{"old":"/api/v1/collections","type":0,"val":"api","end":""},{"old":"/api/v1/collections","type":0,"val":"v1","end":""},{"old":"/api/v1/collections","type":0,"val":"collections","end":""}],
    types: placeholder as Registry['api.collections.index']['types'],
  },
  'api.collections.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/collections/:slug',
    tokens: [{"old":"/api/v1/collections/:slug","type":0,"val":"api","end":""},{"old":"/api/v1/collections/:slug","type":0,"val":"v1","end":""},{"old":"/api/v1/collections/:slug","type":0,"val":"collections","end":""},{"old":"/api/v1/collections/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['api.collections.show']['types'],
  },
  'api.entries.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/collections/:slug/entries',
    tokens: [{"old":"/api/v1/collections/:slug/entries","type":0,"val":"api","end":""},{"old":"/api/v1/collections/:slug/entries","type":0,"val":"v1","end":""},{"old":"/api/v1/collections/:slug/entries","type":0,"val":"collections","end":""},{"old":"/api/v1/collections/:slug/entries","type":1,"val":"slug","end":""},{"old":"/api/v1/collections/:slug/entries","type":0,"val":"entries","end":""}],
    types: placeholder as Registry['api.entries.index']['types'],
  },
  'api.entries.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/collections/:slug/entries/:entrySlug',
    tokens: [{"old":"/api/v1/collections/:slug/entries/:entrySlug","type":0,"val":"api","end":""},{"old":"/api/v1/collections/:slug/entries/:entrySlug","type":0,"val":"v1","end":""},{"old":"/api/v1/collections/:slug/entries/:entrySlug","type":0,"val":"collections","end":""},{"old":"/api/v1/collections/:slug/entries/:entrySlug","type":1,"val":"slug","end":""},{"old":"/api/v1/collections/:slug/entries/:entrySlug","type":0,"val":"entries","end":""},{"old":"/api/v1/collections/:slug/entries/:entrySlug","type":1,"val":"entrySlug","end":""}],
    types: placeholder as Registry['api.entries.show']['types'],
  },
  'api.globals.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/globals',
    tokens: [{"old":"/api/v1/globals","type":0,"val":"api","end":""},{"old":"/api/v1/globals","type":0,"val":"v1","end":""},{"old":"/api/v1/globals","type":0,"val":"globals","end":""}],
    types: placeholder as Registry['api.globals.index']['types'],
  },
  'api.globals.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/globals/:slug',
    tokens: [{"old":"/api/v1/globals/:slug","type":0,"val":"api","end":""},{"old":"/api/v1/globals/:slug","type":0,"val":"v1","end":""},{"old":"/api/v1/globals/:slug","type":0,"val":"globals","end":""},{"old":"/api/v1/globals/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['api.globals.show']['types'],
  },
  'api.redirects.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/redirects',
    tokens: [{"old":"/api/v1/redirects","type":0,"val":"api","end":""},{"old":"/api/v1/redirects","type":0,"val":"v1","end":""},{"old":"/api/v1/redirects","type":0,"val":"redirects","end":""}],
    types: placeholder as Registry['api.redirects.index']['types'],
  },
  'api.sitemap.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/sitemap',
    tokens: [{"old":"/api/v1/sitemap","type":0,"val":"api","end":""},{"old":"/api/v1/sitemap","type":0,"val":"v1","end":""},{"old":"/api/v1/sitemap","type":0,"val":"sitemap","end":""}],
    types: placeholder as Registry['api.sitemap.show']['types'],
  },
  'public.device.code': {
    methods: ["POST"],
    pattern: '/api/device/code',
    tokens: [{"old":"/api/device/code","type":0,"val":"api","end":""},{"old":"/api/device/code","type":0,"val":"device","end":""},{"old":"/api/device/code","type":0,"val":"code","end":""}],
    types: placeholder as Registry['public.device.code']['types'],
  },
  'public.device.token': {
    methods: ["POST"],
    pattern: '/api/device/token',
    tokens: [{"old":"/api/device/token","type":0,"val":"api","end":""},{"old":"/api/device/token","type":0,"val":"device","end":""},{"old":"/api/device/token","type":0,"val":"token","end":""}],
    types: placeholder as Registry['public.device.token']['types'],
  },
  'management.api_tokens.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/api_tokens/me',
    tokens: [{"old":"/api/api_tokens/me","type":0,"val":"api","end":""},{"old":"/api/api_tokens/me","type":0,"val":"api_tokens","end":""},{"old":"/api/api_tokens/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['management.api_tokens.me']['types'],
  },
  'management.api_tokens.rotate': {
    methods: ["POST"],
    pattern: '/api/api_tokens/rotate',
    tokens: [{"old":"/api/api_tokens/rotate","type":0,"val":"api","end":""},{"old":"/api/api_tokens/rotate","type":0,"val":"api_tokens","end":""},{"old":"/api/api_tokens/rotate","type":0,"val":"rotate","end":""}],
    types: placeholder as Registry['management.api_tokens.rotate']['types'],
  },
  'management.service_tokens.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/service_tokens',
    tokens: [{"old":"/api/service_tokens","type":0,"val":"api","end":""},{"old":"/api/service_tokens","type":0,"val":"service_tokens","end":""}],
    types: placeholder as Registry['management.service_tokens.index']['types'],
  },
  'management.service_tokens.store': {
    methods: ["POST"],
    pattern: '/api/service_tokens',
    tokens: [{"old":"/api/service_tokens","type":0,"val":"api","end":""},{"old":"/api/service_tokens","type":0,"val":"service_tokens","end":""}],
    types: placeholder as Registry['management.service_tokens.store']['types'],
  },
  'management.service_tokens.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/service_tokens/:id',
    tokens: [{"old":"/api/service_tokens/:id","type":0,"val":"api","end":""},{"old":"/api/service_tokens/:id","type":0,"val":"service_tokens","end":""},{"old":"/api/service_tokens/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['management.service_tokens.show']['types'],
  },
  'management.service_tokens.reveal': {
    methods: ["POST"],
    pattern: '/api/service_tokens/:id/reveal',
    tokens: [{"old":"/api/service_tokens/:id/reveal","type":0,"val":"api","end":""},{"old":"/api/service_tokens/:id/reveal","type":0,"val":"service_tokens","end":""},{"old":"/api/service_tokens/:id/reveal","type":1,"val":"id","end":""},{"old":"/api/service_tokens/:id/reveal","type":0,"val":"reveal","end":""}],
    types: placeholder as Registry['management.service_tokens.reveal']['types'],
  },
  'management.service_tokens.rotate': {
    methods: ["POST"],
    pattern: '/api/service_tokens/:id/rotate',
    tokens: [{"old":"/api/service_tokens/:id/rotate","type":0,"val":"api","end":""},{"old":"/api/service_tokens/:id/rotate","type":0,"val":"service_tokens","end":""},{"old":"/api/service_tokens/:id/rotate","type":1,"val":"id","end":""},{"old":"/api/service_tokens/:id/rotate","type":0,"val":"rotate","end":""}],
    types: placeholder as Registry['management.service_tokens.rotate']['types'],
  },
  'management.service_tokens.revoke': {
    methods: ["POST"],
    pattern: '/api/service_tokens/:id/revoke',
    tokens: [{"old":"/api/service_tokens/:id/revoke","type":0,"val":"api","end":""},{"old":"/api/service_tokens/:id/revoke","type":0,"val":"service_tokens","end":""},{"old":"/api/service_tokens/:id/revoke","type":1,"val":"id","end":""},{"old":"/api/service_tokens/:id/revoke","type":0,"val":"revoke","end":""}],
    types: placeholder as Registry['management.service_tokens.revoke']['types'],
  },
  'connect.show': {
    methods: ["GET","HEAD"],
    pattern: '/connect',
    tokens: [{"old":"/connect","type":0,"val":"connect","end":""}],
    types: placeholder as Registry['connect.show']['types'],
  },
  'connect.store': {
    methods: ["POST"],
    pattern: '/connect',
    tokens: [{"old":"/connect","type":0,"val":"connect","end":""}],
    types: placeholder as Registry['connect.store']['types'],
  },
  'admin.forms.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/forms',
    tokens: [{"old":"/admin/forms","type":0,"val":"admin","end":""},{"old":"/admin/forms","type":0,"val":"forms","end":""}],
    types: placeholder as Registry['admin.forms.index']['types'],
  },
  'admin.forms.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/forms/new',
    tokens: [{"old":"/admin/forms/new","type":0,"val":"admin","end":""},{"old":"/admin/forms/new","type":0,"val":"forms","end":""},{"old":"/admin/forms/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['admin.forms.create']['types'],
  },
  'admin.forms.store': {
    methods: ["POST"],
    pattern: '/admin/forms',
    tokens: [{"old":"/admin/forms","type":0,"val":"admin","end":""},{"old":"/admin/forms","type":0,"val":"forms","end":""}],
    types: placeholder as Registry['admin.forms.store']['types'],
  },
  'admin.forms.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/forms/:id/edit',
    tokens: [{"old":"/admin/forms/:id/edit","type":0,"val":"admin","end":""},{"old":"/admin/forms/:id/edit","type":0,"val":"forms","end":""},{"old":"/admin/forms/:id/edit","type":1,"val":"id","end":""},{"old":"/admin/forms/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['admin.forms.edit']['types'],
  },
  'admin.forms.update': {
    methods: ["PUT"],
    pattern: '/admin/forms/:id',
    tokens: [{"old":"/admin/forms/:id","type":0,"val":"admin","end":""},{"old":"/admin/forms/:id","type":0,"val":"forms","end":""},{"old":"/admin/forms/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.forms.update']['types'],
  },
  'admin.forms.duplicate': {
    methods: ["POST"],
    pattern: '/admin/forms/:id/duplicate',
    tokens: [{"old":"/admin/forms/:id/duplicate","type":0,"val":"admin","end":""},{"old":"/admin/forms/:id/duplicate","type":0,"val":"forms","end":""},{"old":"/admin/forms/:id/duplicate","type":1,"val":"id","end":""},{"old":"/admin/forms/:id/duplicate","type":0,"val":"duplicate","end":""}],
    types: placeholder as Registry['admin.forms.duplicate']['types'],
  },
  'admin.forms.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/forms/:id',
    tokens: [{"old":"/admin/forms/:id","type":0,"val":"admin","end":""},{"old":"/admin/forms/:id","type":0,"val":"forms","end":""},{"old":"/admin/forms/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.forms.destroy']['types'],
  },
  'admin.lookups.forms': {
    methods: ["GET","HEAD"],
    pattern: '/admin/lookups/forms',
    tokens: [{"old":"/admin/lookups/forms","type":0,"val":"admin","end":""},{"old":"/admin/lookups/forms","type":0,"val":"lookups","end":""},{"old":"/admin/lookups/forms","type":0,"val":"forms","end":""}],
    types: placeholder as Registry['admin.lookups.forms']['types'],
  },
  'admin.forms.submissions': {
    methods: ["GET","HEAD"],
    pattern: '/admin/forms/:formId/submissions',
    tokens: [{"old":"/admin/forms/:formId/submissions","type":0,"val":"admin","end":""},{"old":"/admin/forms/:formId/submissions","type":0,"val":"forms","end":""},{"old":"/admin/forms/:formId/submissions","type":1,"val":"formId","end":""},{"old":"/admin/forms/:formId/submissions","type":0,"val":"submissions","end":""}],
    types: placeholder as Registry['admin.forms.submissions']['types'],
  },
  'admin.forms.submissions.export': {
    methods: ["GET","HEAD"],
    pattern: '/admin/forms/:formId/submissions/export',
    tokens: [{"old":"/admin/forms/:formId/submissions/export","type":0,"val":"admin","end":""},{"old":"/admin/forms/:formId/submissions/export","type":0,"val":"forms","end":""},{"old":"/admin/forms/:formId/submissions/export","type":1,"val":"formId","end":""},{"old":"/admin/forms/:formId/submissions/export","type":0,"val":"submissions","end":""},{"old":"/admin/forms/:formId/submissions/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['admin.forms.submissions.export']['types'],
  },
  'admin.submissions.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/submissions',
    tokens: [{"old":"/admin/submissions","type":0,"val":"admin","end":""},{"old":"/admin/submissions","type":0,"val":"submissions","end":""}],
    types: placeholder as Registry['admin.submissions.index']['types'],
  },
  'admin.submissions.bulk': {
    methods: ["POST"],
    pattern: '/admin/submissions/bulk',
    tokens: [{"old":"/admin/submissions/bulk","type":0,"val":"admin","end":""},{"old":"/admin/submissions/bulk","type":0,"val":"submissions","end":""},{"old":"/admin/submissions/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin.submissions.bulk']['types'],
  },
  'admin.submissions.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/submissions/:id',
    tokens: [{"old":"/admin/submissions/:id","type":0,"val":"admin","end":""},{"old":"/admin/submissions/:id","type":0,"val":"submissions","end":""},{"old":"/admin/submissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.submissions.show']['types'],
  },
  'admin.submissions.update': {
    methods: ["PUT"],
    pattern: '/admin/submissions/:id',
    tokens: [{"old":"/admin/submissions/:id","type":0,"val":"admin","end":""},{"old":"/admin/submissions/:id","type":0,"val":"submissions","end":""},{"old":"/admin/submissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.submissions.update']['types'],
  },
  'admin.submissions.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/submissions/:id',
    tokens: [{"old":"/admin/submissions/:id","type":0,"val":"admin","end":""},{"old":"/admin/submissions/:id","type":0,"val":"submissions","end":""},{"old":"/admin/submissions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.submissions.destroy']['types'],
  },
  'admin.submissions.file': {
    methods: ["GET","HEAD"],
    pattern: '/admin/submissions/:id/files/:field',
    tokens: [{"old":"/admin/submissions/:id/files/:field","type":0,"val":"admin","end":""},{"old":"/admin/submissions/:id/files/:field","type":0,"val":"submissions","end":""},{"old":"/admin/submissions/:id/files/:field","type":1,"val":"id","end":""},{"old":"/admin/submissions/:id/files/:field","type":0,"val":"files","end":""},{"old":"/admin/submissions/:id/files/:field","type":1,"val":"field","end":""}],
    types: placeholder as Registry['admin.submissions.file']['types'],
  },
  'admin.settings.forms.edit': {
    methods: ["GET","HEAD"],
    pattern: '/admin/settings/forms',
    tokens: [{"old":"/admin/settings/forms","type":0,"val":"admin","end":""},{"old":"/admin/settings/forms","type":0,"val":"settings","end":""},{"old":"/admin/settings/forms","type":0,"val":"forms","end":""}],
    types: placeholder as Registry['admin.settings.forms.edit']['types'],
  },
  'admin.settings.forms.update': {
    methods: ["PUT"],
    pattern: '/admin/settings/forms',
    tokens: [{"old":"/admin/settings/forms","type":0,"val":"admin","end":""},{"old":"/admin/settings/forms","type":0,"val":"settings","end":""},{"old":"/admin/settings/forms","type":0,"val":"forms","end":""}],
    types: placeholder as Registry['admin.settings.forms.update']['types'],
  },
  'public.forms.submit': {
    methods: ["POST"],
    pattern: '/forms/:slug',
    tokens: [{"old":"/forms/:slug","type":0,"val":"forms","end":""},{"old":"/forms/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['public.forms.submit']['types'],
  },
  'api.forms.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/forms',
    tokens: [{"old":"/api/v1/forms","type":0,"val":"api","end":""},{"old":"/api/v1/forms","type":0,"val":"v1","end":""},{"old":"/api/v1/forms","type":0,"val":"forms","end":""}],
    types: placeholder as Registry['api.forms.index']['types'],
  },
  'api.forms.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/forms/:slug',
    tokens: [{"old":"/api/v1/forms/:slug","type":0,"val":"api","end":""},{"old":"/api/v1/forms/:slug","type":0,"val":"v1","end":""},{"old":"/api/v1/forms/:slug","type":0,"val":"forms","end":""},{"old":"/api/v1/forms/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['api.forms.show']['types'],
  },
  'admin.media.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/media',
    tokens: [{"old":"/admin/media","type":0,"val":"admin","end":""},{"old":"/admin/media","type":0,"val":"media","end":""}],
    types: placeholder as Registry['admin.media.index']['types'],
  },
  'admin.media.create': {
    methods: ["GET","HEAD"],
    pattern: '/admin/media/new',
    tokens: [{"old":"/admin/media/new","type":0,"val":"admin","end":""},{"old":"/admin/media/new","type":0,"val":"media","end":""},{"old":"/admin/media/new","type":0,"val":"new","end":""}],
    types: placeholder as Registry['admin.media.create']['types'],
  },
  'admin.media.lookup': {
    methods: ["GET","HEAD"],
    pattern: '/admin/media/lookup',
    tokens: [{"old":"/admin/media/lookup","type":0,"val":"admin","end":""},{"old":"/admin/media/lookup","type":0,"val":"media","end":""},{"old":"/admin/media/lookup","type":0,"val":"lookup","end":""}],
    types: placeholder as Registry['admin.media.lookup']['types'],
  },
  'admin.media.store': {
    methods: ["POST"],
    pattern: '/admin/media/uploads',
    tokens: [{"old":"/admin/media/uploads","type":0,"val":"admin","end":""},{"old":"/admin/media/uploads","type":0,"val":"media","end":""},{"old":"/admin/media/uploads","type":0,"val":"uploads","end":""}],
    types: placeholder as Registry['admin.media.store']['types'],
  },
  'admin.media.bulk': {
    methods: ["POST"],
    pattern: '/admin/media/bulk',
    tokens: [{"old":"/admin/media/bulk","type":0,"val":"admin","end":""},{"old":"/admin/media/bulk","type":0,"val":"media","end":""},{"old":"/admin/media/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin.media.bulk']['types'],
  },
  'admin.media.folders.store': {
    methods: ["POST"],
    pattern: '/admin/media/folders',
    tokens: [{"old":"/admin/media/folders","type":0,"val":"admin","end":""},{"old":"/admin/media/folders","type":0,"val":"media","end":""},{"old":"/admin/media/folders","type":0,"val":"folders","end":""}],
    types: placeholder as Registry['admin.media.folders.store']['types'],
  },
  'admin.media.folders.update': {
    methods: ["PUT"],
    pattern: '/admin/media/folders',
    tokens: [{"old":"/admin/media/folders","type":0,"val":"admin","end":""},{"old":"/admin/media/folders","type":0,"val":"media","end":""},{"old":"/admin/media/folders","type":0,"val":"folders","end":""}],
    types: placeholder as Registry['admin.media.folders.update']['types'],
  },
  'admin.media.folders.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/media/folders',
    tokens: [{"old":"/admin/media/folders","type":0,"val":"admin","end":""},{"old":"/admin/media/folders","type":0,"val":"media","end":""},{"old":"/admin/media/folders","type":0,"val":"folders","end":""}],
    types: placeholder as Registry['admin.media.folders.destroy']['types'],
  },
  'admin.media.update': {
    methods: ["PUT"],
    pattern: '/admin/media/:id',
    tokens: [{"old":"/admin/media/:id","type":0,"val":"admin","end":""},{"old":"/admin/media/:id","type":0,"val":"media","end":""},{"old":"/admin/media/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.media.update']['types'],
  },
  'admin.media.replace': {
    methods: ["PUT"],
    pattern: '/admin/media/:id/file',
    tokens: [{"old":"/admin/media/:id/file","type":0,"val":"admin","end":""},{"old":"/admin/media/:id/file","type":0,"val":"media","end":""},{"old":"/admin/media/:id/file","type":1,"val":"id","end":""},{"old":"/admin/media/:id/file","type":0,"val":"file","end":""}],
    types: placeholder as Registry['admin.media.replace']['types'],
  },
  'admin.media.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/media/:id',
    tokens: [{"old":"/admin/media/:id","type":0,"val":"admin","end":""},{"old":"/admin/media/:id","type":0,"val":"media","end":""},{"old":"/admin/media/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.media.destroy']['types'],
  },
  'api.assets.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/assets',
    tokens: [{"old":"/api/v1/assets","type":0,"val":"api","end":""},{"old":"/api/v1/assets","type":0,"val":"v1","end":""},{"old":"/api/v1/assets","type":0,"val":"assets","end":""}],
    types: placeholder as Registry['api.assets.index']['types'],
  },
  'api.assets.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/assets/:id',
    tokens: [{"old":"/api/v1/assets/:id","type":0,"val":"api","end":""},{"old":"/api/v1/assets/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/assets/:id","type":0,"val":"assets","end":""},{"old":"/api/v1/assets/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api.assets.show']['types'],
  },
  'branding.css': {
    methods: ["GET","HEAD"],
    pattern: '/branding.css',
    tokens: [{"old":"/branding.css","type":0,"val":"branding.css","end":""}],
    types: placeholder as Registry['branding.css']['types'],
  },
  'health': {
    methods: ["GET","HEAD"],
    pattern: '/up',
    tokens: [{"old":"/up","type":0,"val":"up","end":""}],
    types: placeholder as Registry['health']['types'],
  },
  'sitemap.show': {
    methods: ["GET","HEAD"],
    pattern: '/sitemap.xml',
    tokens: [{"old":"/sitemap.xml","type":0,"val":"sitemap.xml","end":""}],
    types: placeholder as Registry['sitemap.show']['types'],
  },
  'robots.show': {
    methods: ["GET","HEAD"],
    pattern: '/robots.txt',
    tokens: [{"old":"/robots.txt","type":0,"val":"robots.txt","end":""}],
    types: placeholder as Registry['robots.show']['types'],
  },
  'site.home': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['site.home']['types'],
  },
  'site.page': {
    methods: ["GET","HEAD"],
    pattern: '/*',
    tokens: [{"old":"/*","type":2,"val":"*","end":""}],
    types: placeholder as Registry['site.page']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
