import { Env } from '@adonisjs/core/env'

export default await Env.create(new URL('../', import.meta.url), {
  NODE_ENV: Env.schema.enum(['development', 'production', 'test'] as const),
  PORT: Env.schema.number(),
  HOST: Env.schema.string({ format: 'host' }),
  LOG_LEVEL: Env.schema.string(),
  APP_KEY: Env.schema.secret(),
  APP_URL: Env.schema.string({ format: 'url', tld: false }),
  SESSION_DRIVER: Env.schema.enum(['cookie', 'memory', 'database'] as const),
  DRIVE_DISK: Env.schema.enum(['fs'] as const),
  MAIL_MAILER: Env.schema.enum(['smtp'] as const),
  MAIL_FROM_NAME: Env.schema.string(),
  MAIL_FROM_ADDRESS: Env.schema.string(),
  SMTP_HOST: Env.schema.string(),
  SMTP_PORT: Env.schema.number(),
  SMTP_USERNAME: Env.schema.string.optional(),
  SMTP_PASSWORD: Env.schema.string.optional(),
  LIMITER_STORE: Env.schema.enum(['database', 'memory'] as const),
  ADMIN_EMAIL: Env.schema.string.optional(),
  ADMIN_PASSWORD: Env.schema.string.optional(),
  QUEUE_WORKER: Env.schema.enum.optional(['inline', 'off'] as const),
  CMS_ALLOW_PRIVATE_WEBHOOKS: Env.schema.boolean.optional(),
  SITE_KEY: Env.schema.string.optional(),
  CMS_FORCE_SSL: Env.schema.boolean.optional(),
  ASSUME_SSL: Env.schema.boolean.optional(),
  CMS_CSP: Env.schema.enum.optional(['on', 'report-only', 'off'] as const),
  CMS_TRASH_DAYS: Env.schema.number.optional(),
  CMS_VERSIONS_KEEP: Env.schema.number.optional(),
  CMS_DELIVERY_RATE_LIMIT: Env.schema.number.optional(),
  CMS_GITHUB_TOKEN: Env.schema.string.optional(),
  CMS_GITHUB_API_URL: Env.schema.string.optional(),
  CMS_UPDATE_REPO: Env.schema.string.optional(),
  CMS_UPDATE_CHECK: Env.schema.boolean.optional(),
  CMS_UPDATES: Env.schema.enum.optional(['manual', 'docker'] as const),
  CMS_BACKUP_DIR: Env.schema.string.optional(),
  CMS_BACKUP_KEEP: Env.schema.number.optional(),
  CMS_BACKUP_COMMAND: Env.schema.string.optional(),
  CMS_BACKUP_NIGHTLY: Env.schema.boolean.optional(),
})
